FROM node:carbon-alpine

WORKDIR /app
RUN yarn global add wait-on

EXPOSE 4000

# CMD wait-on -l tcp:db:5432 tcp:elasticsearch:9200 && yarn install && yarn dev
CMD wait-on -l tcp:db:5432 && yarn install && yarn dev
