FROM node:carbon-alpine

WORKDIR /app

COPY frontend .

# install deps for dev version
# this allows us to build the webpack prod version
RUN yarn install --dev

# info on ARG/ENV and build step: https://github.com/docker/compose/issues/1837
ARG NODE_ENV
ENV NODE_ENV "$NODE_ENV"

RUN yarn build
RUN yarn global add forever

EXPOSE 3000

CMD forever server.js
