version: "3"

services:
  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile
    image: otwartepanstwo-server
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./data/files:/data/files # persisted downloads
      - ./data/uploads:/data/uploads # persisted uploads
    depends_on:
      - frontend
      - api
      - publicapi

  frontend:
    build:
      context: ../.
      dockerfile: docker/frontend/Dockerfile.dev
    image: otwartepanstwo-frontend-dev
    restart: on-failure
    environment:
      - NODE_ENV=development
      - AUTH0_DOMAIN # env passed from shell
      - AUTH0_CLIENTID # env passed from shell
      - AUTH0_REDIRECT # env passed from shell
      - ADMIN_EMAILS # env passed from shell
    volumes:
      - ./../frontend:/app
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones
    ports:
      - "3000:3000"

  api:
    build:
      context: ../.
      dockerfile: docker/api/Dockerfile.dev
    image: otwartepanstwo-api-dev
    restart: on-failure
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD # env passed from shell
      - POSTGRES_USER # env passed from shell
      - POSTGRES_DB # env passed from shell
      - AUTH0_DOMAIN # env passed from shell
      - AUTH0_CLIENTID # env passed from shell
      - AUTH0_REDIRECT # env passed from shell
    volumes:
      - ./../api:/app
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones
      - ./data/files:/data/files # persisted downloads
      - ./data/uploads:/data/uploads # persisted uploads
    depends_on:
      - db
    ports:
      - "4000:4000"

  publicapi:
    build:
      context: ../.
      dockerfile: docker/public-api/Dockerfile.dev
    image: otwartepanstwo-public-api-dev
    restart: on-failure
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD # env passed from shell
      - POSTGRES_USER # env passed from shell
      - POSTGRES_DB # env passed from shell
    volumes:
      - ./../public-api:/app
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones
    depends_on:
      - db
    ports:
      - "5000:5000"

  fetcher:
    build:
      context: ../.
      dockerfile: docker/fetcher/Dockerfile.dev
    image: otwartepanstwo-fetcher-dev
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD # env passed from shell
      - POSTGRES_USER # env passed from shell
      - POSTGRES_DB # env passed from shell
      - MAILGUN_API_KEY # env passed from shell
      - MAILGUN_DOMAIN # env passed from shell
      - DEV_CRAWLERS # list of crawlers to run in dev mode
      - MAIN_URL # url used in subscriptions mails from fetcher
    volumes:
      - ./../fetcher:/app
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones
      - ./data/files:/data/files # persisted downloads
    depends_on:
      - db

  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD # env passed from shell
      - POSTGRES_USER # env passed from shell
      - POSTGRES_DB # env passed from shell
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./../db/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"
