version: "3.2"

services:
  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile
    image: otwartepanstwo-server
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./data/files:/data/files # persisted downloads
      - ./data/uploads:/data/uploads # persisted downloads
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: ../.
      dockerfile: docker/frontend/Dockerfile.prod
      args:
        - NODE_ENV=production
        - AUTH0_DOMAIN # env passed from shell
        - AUTH0_CLIENTID # env passed from shell
        - AUTH0_REDIRECT # env passed from shell
        - ADMIN_EMAILS # env passed from shell
    image: otwartepanstwo-frontend-prod
    restart: on-failure
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  api:
    build:
      context: ../.
      dockerfile: docker/api/Dockerfile.prod
      args:
        - NODE_ENV=production
    image: otwartepanstwo-api-prod
    restart: on-failure
    environment:
      - NODE_ENV=production
      - POSTGRES_PASSWORD # env passed from shell
      - POSTGRES_USER # env passed from shell
      - POSTGRES_DB # env passed from shell
      - AUTH0_DOMAIN # env passed from shell
      - AUTH0_CLIENTID # env passed from shell
      - AUTH0_REDIRECT # env passed from shell
    volumes:
      - ./data/files:/data/files # persisted downloads
      - ./data/uploads:/data/uploads # persisted downloads
    depends_on:
      - db
      # - elasticsearch
    ports:
      - "4000:4000"

  fetcher:
    build:
      context: ../.
      dockerfile: docker/fetcher/Dockerfile.prod
      args:
        - NODE_ENV=production
    image: otwartepanstwo-fetcher-prod
    environment:
      - NODE_ENV=production
      - POSTGRES_PASSWORD # env passed from shell
      - POSTGRES_USER # env passed from shell
      - POSTGRES_DB # env passed from shell
      - MAILGUN_API_KEY # env passed from shell
      - MAILGUN_DOMAIN # env passed from shell
      - MAIN_URL # url used in subscriptions mails from fetcher
    volumes:
      - ./data/files:/data/files # persisted downloads
    depends_on:
      - db

  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD # env passed from shell
      - POSTGRES_USER # env passed from shell
      - POSTGRES_DB # env passed from shell
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./../db/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"
