FROM node:latest

RUN apt-get update
RUN apt-get -y install poppler-utils

RUN yarn global add wait-on

# set up script
WORKDIR /app

CMD wait-on -l tcp:db:5432 tcp:elasticsearch:9200 && yarn install && yarn dev
